// Vietnamese administrative divisions data for address dropdowns
// Organized: Tỉnh/Thành Phố → Quận/Huyện → Phường/Xã

const VIETNAM_PROVINCES = [
  {
    name: "Hồ Chí Minh",
    districts: [
      {
        name: "Quận 1",
        wards: [
          "Phường Bến Nghé",
          "Phường Bến Thành",
          "Phường Cầu Kho",
          "Phường Cầu Ông Lãnh",
          "Phường Cô Giang",
          "Phường Đa Kao",
          "Phường Nguyễn Cư Trinh",
          "Phường Nguyễn Thái Bình",
          "Phường Phạm Ngũ Lão",
          "Phường Tân Định",
        ],
      },
      {
        name: "Quận 3",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường Võ Thị Sáu",
        ],
      },
      {
        name: "Quận 4",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 6",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 16",
          "Phường 18",
        ],
      },
      {
        name: "Quận 5",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
        ],
      },
      {
        name: "Quận 6",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
        ],
      },
      {
        name: "Quận 7",
        wards: [
          "Phường Bình Thuận",
          "Phường Phú Mỹ",
          "Phường Phú Thuận",
          "Phường Tân Hưng",
          "Phường Tân Kiểng",
          "Phường Tân Phong",
          "Phường Tân Phú",
          "Phường Tân Quy",
          "Phường Tân Thuận Đông",
          "Phường Tân Thuận Tây",
        ],
      },
      {
        name: "Quận 8",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 16",
        ],
      },
      {
        name: "Quận 10",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
        ],
      },
      {
        name: "Quận 11",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 16",
        ],
      },
      {
        name: "Quận 12",
        wards: [
          "Phường An Phú Đông",
          "Phường Đông Hưng Thuận",
          "Phường Hiệp Thành",
          "Phường Tân Chánh Hiệp",
          "Phường Tân Hưng Thuận",
          "Phường Tân Thới Hiệp",
          "Phường Tân Thới Nhất",
          "Phường Thạnh Lộc",
          "Phường Thạnh Xuân",
          "Phường Thới An",
          "Phường Trung Mỹ Tây",
        ],
      },
      {
        name: "Quận Bình Tân",
        wards: [
          "Phường An Lạc",
          "Phường An Lạc A",
          "Phường Bình Hưng Hòa",
          "Phường Bình Hưng Hòa A",
          "Phường Bình Hưng Hòa B",
          "Phường Bình Trị Đông",
          "Phường Bình Trị Đông A",
          "Phường Bình Trị Đông B",
          "Phường Tân Tạo",
          "Phường Tân Tạo A",
        ],
      },
      {
        name: "Quận Bình Thạnh",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 17",
          "Phường 19",
          "Phường 21",
          "Phường 22",
          "Phường 24",
          "Phường 25",
          "Phường 26",
          "Phường 27",
          "Phường 28",
        ],
      },
      {
        name: "Quận Gò Vấp",
        wards: [
          "Phường 1",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 16",
          "Phường 17",
        ],
      },
      {
        name: "Quận Phú Nhuận",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 17",
        ],
      },
      {
        name: "Quận Tân Bình",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
        ],
      },
      {
        name: "Quận Tân Phú",
        wards: [
          "Phường Hiệp Tân",
          "Phường Hòa Thạnh",
          "Phường Phú Thạnh",
          "Phường Phú Thọ Hòa",
          "Phường Phú Trung",
          "Phường Sơn Kỳ",
          "Phường Tân Quý",
          "Phường Tân Sơn Nhì",
          "Phường Tân Thành",
          "Phường Tân Thới Hòa",
          "Phường Tây Thạnh",
        ],
      },
      {
        name: "Thành phố Thủ Đức",
        wards: [
          "Phường An Khánh",
          "Phường An Lợi Đông",
          "Phường An Phú",
          "Phường Bình Chiểu",
          "Phường Bình Thọ",
          "Phường Bình Trưng Đông",
          "Phường Bình Trưng Tây",
          "Phường Cát Lái",
          "Phường Hiệp Bình Chánh",
          "Phường Hiệp Bình Phước",
          "Phường Hiệp Phú",
          "Phường Linh Chiểu",
          "Phường Linh Đông",
          "Phường Linh Tây",
          "Phường Linh Trung",
          "Phường Linh Xuân",
          "Phường Long Bình",
          "Phường Long Phước",
          "Phường Long Thạnh Mỹ",
          "Phường Long Trường",
          "Phường Phú Hữu",
          "Phường Phước Bình",
          "Phường Phước Long A",
          "Phường Phước Long B",
          "Phường Tam Bình",
          "Phường Tam Phú",
          "Phường Tân Phú",
          "Phường Thảo Điền",
          "Phường Thạnh Mỹ Lợi",
          "Phường Thủ Thiêm",
          "Phường Trường Thạnh",
          "Phường Trường Thọ",
        ],
      },
      {
        name: "Huyện Bình Chánh",
        wards: [
          "Xã An Phú Tây",
          "Xã Bình Chánh",
          "Xã Bình Hưng",
          "Xã Bình Lợi",
          "Xã Đa Phước",
          "Xã Hưng Long",
          "Xã Lê Minh Xuân",
          "Xã Phạm Văn Hai",
          "Xã Phong Phú",
          "Xã Quy Đức",
          "Xã Tân Kiên",
          "Xã Tân Nhựt",
          "Xã Tân Quý Tây",
          "Xã Vĩnh Lộc A",
          "Xã Vĩnh Lộc B",
          "Thị trấn Tân Túc",
        ],
      },
      {
        name: "Huyện Cần Giờ",
        wards: [
          "Xã An Thới Đông",
          "Xã Bình Khánh",
          "Xã Long Hòa",
          "Xã Lý Nhơn",
          "Xã Tam Thôn Hiệp",
          "Xã Thạnh An",
          "Thị trấn Cần Thạnh",
        ],
      },
      {
        name: "Huyện Củ Chi",
        wards: [
          "Xã An Nhơn Tây",
          "Xã An Phú",
          "Xã Bình Mỹ",
          "Xã Hòa Phú",
          "Xã Nhuận Đức",
          "Xã Phạm Văn Cội",
          "Xã Phú Hòa Đông",
          "Xã Phú Mỹ Hưng",
          "Xã Phước Hiệp",
          "Xã Phước Thạnh",
          "Xã Phước Vĩnh An",
          "Xã Tân An Hội",
          "Xã Tân Phú Trung",
          "Xã Tân Thạnh Đông",
          "Xã Tân Thạnh Tây",
          "Xã Tân Thông Hội",
          "Xã Thái Mỹ",
          "Xã Trung An",
          "Xã Trung Lập Hạ",
          "Xã Trung Lập Thượng",
          "Thị trấn Củ Chi",
        ],
      },
      {
        name: "Huyện Hóc Môn",
        wards: [
          "Xã Bà Điểm",
          "Xã Đông Thạnh",
          "Xã Nhị Bình",
          "Xã Tân Hiệp",
          "Xã Tân Thới Nhì",
          "Xã Thới Tam Thôn",
          "Xã Trung Chánh",
          "Xã Xuân Thới Đông",
          "Xã Xuân Thới Sơn",
          "Xã Xuân Thới Thượng",
          "Thị trấn Hóc Môn",
        ],
      },
      {
        name: "Huyện Nhà Bè",
        wards: [
          "Xã Hiệp Phước",
          "Xã Long Thới",
          "Xã Nhơn Đức",
          "Xã Phú Xuân",
          "Xã Phước Kiển",
          "Xã Phước Lộc",
          "Thị trấn Nhà Bè",
        ],
      },
    ],
  },
  {
    name: "Hà Nội",
    districts: [
      {
        name: "Quận Ba Đình",
        wards: [
          "Phường Cống Vị",
          "Phường Điện Biên",
          "Phường Đội Cấn",
          "Phường Giảng Võ",
          "Phường Kim Mã",
          "Phường Liễu Giai",
          "Phường Ngọc Hà",
          "Phường Ngọc Khánh",
          "Phường Nguyễn Trung Trực",
          "Phường Phúc Xá",
          "Phường Quán Thánh",
          "Phường Thành Công",
          "Phường Trúc Bạch",
          "Phường Vĩnh Phúc",
        ],
      },
      {
        name: "Quận Hoàn Kiếm",
        wards: [
          "Phường Chương Dương",
          "Phường Cửa Đông",
          "Phường Cửa Nam",
          "Phường Đồng Xuân",
          "Phường Hàng Bạc",
          "Phường Hàng Bài",
          "Phường Hàng Bông",
          "Phường Hàng Bồ",
          "Phường Hàng Buồm",
          "Phường Hàng Đào",
          "Phường Hàng Gai",
          "Phường Hàng Mã",
          "Phường Hàng Trống",
          "Phường Lý Thái Tổ",
          "Phường Phan Chu Trinh",
          "Phường Phúc Tân",
          "Phường Tràng Tiền",
          "Phường Trần Hưng Đạo",
        ],
      },
      {
        name: "Quận Đống Đa",
        wards: [
          "Phường Cát Linh",
          "Phường Hàng Bột",
          "Phường Khâm Thiên",
          "Phường Khương Thượng",
          "Phường Kim Liên",
          "Phường Láng Hạ",
          "Phường Láng Thượng",
          "Phường Nam Đồng",
          "Phường Ngã Tư Sở",
          "Phường Ô Chợ Dừa",
          "Phường Phương Liên",
          "Phường Phương Mai",
          "Phường Quang Trung",
          "Phường Quốc Tử Giám",
          "Phường Thịnh Quang",
          "Phường Thổ Quan",
          "Phường Trung Liệt",
          "Phường Trung Phụng",
          "Phường Trung Tự",
          "Phường Văn Chương",
          "Phường Văn Miếu",
        ],
      },
      {
        name: "Quận Hai Bà Trưng",
        wards: [
          "Phường Bách Khoa",
          "Phường Bạch Đằng",
          "Phường Bạch Mai",
          "Phường Cầu Dền",
          "Phường Đống Mác",
          "Phường Đồng Nhân",
          "Phường Đồng Tâm",
          "Phường Lê Đại Hành",
          "Phường Minh Khai",
          "Phường Ngô Thì Nhậm",
          "Phường Nguyễn Du",
          "Phường Phạm Đình Hổ",
          "Phường Phố Huế",
          "Phường Quỳnh Lôi",
          "Phường Quỳnh Mai",
          "Phường Thanh Lương",
          "Phường Thanh Nhàn",
          "Phường Trương Định",
          "Phường Vĩnh Tuy",
        ],
      },
      {
        name: "Quận Cầu Giấy",
        wards: [
          "Phường Dịch Vọng",
          "Phường Dịch Vọng Hậu",
          "Phường Mai Dịch",
          "Phường Nghĩa Đô",
          "Phường Nghĩa Tân",
          "Phường Quan Hoa",
          "Phường Trung Hòa",
          "Phường Yên Hòa",
        ],
      },
      {
        name: "Quận Thanh Xuân",
        wards: [
          "Phường Hạ Đình",
          "Phường Khương Đình",
          "Phường Khương Mai",
          "Phường Khương Trung",
          "Phường Kim Giang",
          "Phường Nhân Chính",
          "Phường Phương Liệt",
          "Phường Thanh Xuân Bắc",
          "Phường Thanh Xuân Nam",
          "Phường Thanh Xuân Trung",
          "Phường Thượng Đình",
        ],
      },
      {
        name: "Quận Hoàng Mai",
        wards: [
          "Phường Đại Kim",
          "Phường Định Công",
          "Phường Giáp Bát",
          "Phường Hoàng Liệt",
          "Phường Hoàng Văn Thụ",
          "Phường Lĩnh Nam",
          "Phường Mai Động",
          "Phường Tân Mai",
          "Phường Thanh Trì",
          "Phường Thịnh Liệt",
          "Phường Trần Phú",
          "Phường Tương Mai",
          "Phường Vĩnh Hưng",
          "Phường Yên Sở",
        ],
      },
      {
        name: "Quận Long Biên",
        wards: [
          "Phường Bồ Đề",
          "Phường Cự Khối",
          "Phường Đức Giang",
          "Phường Giang Biên",
          "Phường Gia Thụy",
          "Phường Long Biên",
          "Phường Ngọc Lâm",
          "Phường Ngọc Thụy",
          "Phường Phúc Đồng",
          "Phường Phúc Lợi",
          "Phường Sài Đồng",
          "Phường Thạch Bàn",
          "Phường Thượng Thanh",
          "Phường Việt Hưng",
        ],
      },
      {
        name: "Quận Tây Hồ",
        wards: [
          "Phường Bưởi",
          "Phường Nhật Tân",
          "Phường Phú Thượng",
          "Phường Quảng An",
          "Phường Thụy Khuê",
          "Phường Tứ Liên",
          "Phường Xuân La",
          "Phường Yên Phụ",
        ],
      },
      {
        name: "Quận Nam Từ Liêm",
        wards: [
          "Phường Cầu Diễn",
          "Phường Đại Mỗ",
          "Phường Mễ Trì",
          "Phường Mỹ Đình 1",
          "Phường Mỹ Đình 2",
          "Phường Phú Đô",
          "Phường Phương Canh",
          "Phường Tây Mỗ",
          "Phường Trung Văn",
          "Phường Xuân Phương",
        ],
      },
      {
        name: "Quận Bắc Từ Liêm",
        wards: [
          "Phường Cổ Nhuế 1",
          "Phường Cổ Nhuế 2",
          "Phường Đông Ngạc",
          "Phường Đức Thắng",
          "Phường Liên Mạc",
          "Phường Minh Khai",
          "Phường Phú Diễn",
          "Phường Phúc Diễn",
          "Phường Tây Tựu",
          "Phường Thượng Cát",
          "Phường Thụy Phương",
          "Phường Xuân Đỉnh",
          "Phường Xuân Tảo",
        ],
      },
      {
        name: "Quận Hà Đông",
        wards: [
          "Phường Biên Giang",
          "Phường Dương Nội",
          "Phường Đồng Mai",
          "Phường Hà Cầu",
          "Phường Kiến Hưng",
          "Phường La Khê",
          "Phường Mỗ Lao",
          "Phường Nguyễn Trãi",
          "Phường Phú La",
          "Phường Phú Lãm",
          "Phường Phú Lương",
          "Phường Phúc La",
          "Phường Quang Trung",
          "Phường Vạn Phúc",
          "Phường Văn Quán",
          "Phường Yên Nghĩa",
          "Phường Yết Kiêu",
        ],
      },
    ],
  },
  {
    name: "Đà Nẵng",
    districts: [
      {
        name: "Quận Hải Châu",
        wards: [
          "Phường Bình Hiên",
          "Phường Bình Thuận",
          "Phường Hải Châu I",
          "Phường Hải Châu II",
          "Phường Hòa Cường Bắc",
          "Phường Hòa Cường Nam",
          "Phường Hòa Thuận Đông",
          "Phường Hòa Thuận Tây",
          "Phường Nam Dương",
          "Phường Phước Ninh",
          "Phường Thạch Thang",
          "Phường Thanh Bình",
          "Phường Thuận Phước",
        ],
      },
      {
        name: "Quận Thanh Khê",
        wards: [
          "Phường An Khê",
          "Phường Chính Gián",
          "Phường Hòa Khê",
          "Phường Tam Thuận",
          "Phường Tân Chính",
          "Phường Thạc Gián",
          "Phường Thanh Khê Đông",
          "Phường Thanh Khê Tây",
          "Phường Vĩnh Trung",
          "Phường Xuân Hà",
        ],
      },
      {
        name: "Quận Sơn Trà",
        wards: [
          "Phường An Hải Bắc",
          "Phường An Hải Đông",
          "Phường An Hải Tây",
          "Phường Mân Thái",
          "Phường Nại Hiên Đông",
          "Phường Phước Mỹ",
          "Phường Thọ Quang",
        ],
      },
      {
        name: "Quận Ngũ Hành Sơn",
        wards: [
          "Phường Hòa Hải",
          "Phường Hòa Quý",
          "Phường Khuê Mỹ",
          "Phường Mỹ An",
        ],
      },
      {
        name: "Quận Liên Chiểu",
        wards: [
          "Phường Hòa Hiệp Bắc",
          "Phường Hòa Hiệp Nam",
          "Phường Hòa Khánh Bắc",
          "Phường Hòa Khánh Nam",
          "Phường Hòa Minh",
        ],
      },
      {
        name: "Quận Cẩm Lệ",
        wards: [
          "Phường Hòa An",
          "Phường Hòa Phát",
          "Phường Hòa Thọ Đông",
          "Phường Hòa Thọ Tây",
          "Phường Hòa Xuân",
          "Phường Khuê Trung",
        ],
      },
      {
        name: "Huyện Hòa Vang",
        wards: [
          "Xã Hòa Bắc",
          "Xã Hòa Châu",
          "Xã Hòa Khương",
          "Xã Hòa Liên",
          "Xã Hòa Nhơn",
          "Xã Hòa Ninh",
          "Xã Hòa Phong",
          "Xã Hòa Phú",
          "Xã Hòa Phước",
          "Xã Hòa Sơn",
          "Xã Hòa Tiến",
        ],
      },
    ],
  },
  {
    name: "Cần Thơ",
    districts: [
      {
        name: "Quận Ninh Kiều",
        wards: [
          "Phường An Bình",
          "Phường An Hòa",
          "Phường An Khánh",
          "Phường An Nghiệp",
          "Phường An Phú",
          "Phường Cái Khế",
          "Phường Hưng Lợi",
          "Phường Tân An",
          "Phường Thới Bình",
          "Phường Xuân Khánh",
        ],
      },
      {
        name: "Quận Bình Thủy",
        wards: [
          "Phường An Thới",
          "Phường Bình Thủy",
          "Phường Bùi Hữu Nghĩa",
          "Phường Long Hòa",
          "Phường Long Tuyền",
          "Phường Thới An Đông",
          "Phường Trà An",
          "Phường Trà Nóc",
        ],
      },
      {
        name: "Quận Cái Răng",
        wards: [
          "Phường Ba Láng",
          "Phường Hưng Phú",
          "Phường Hưng Thạnh",
          "Phường Lê Bình",
          "Phường Phú Thứ",
          "Phường Tân Phú",
          "Phường Thường Thạnh",
        ],
      },
    ],
  },
  {
    name: "Hải Phòng",
    districts: [
      {
        name: "Quận Hồng Bàng",
        wards: [
          "Phường Hoàng Văn Thụ",
          "Phường Hùng Vương",
          "Phường Minh Khai",
          "Phường Phan Bội Châu",
          "Phường Quán Toan",
          "Phường Sở Dầu",
          "Phường Thượng Lý",
          "Phường Trại Chuối",
        ],
      },
      {
        name: "Quận Ngô Quyền",
        wards: [
          "Phường Cầu Đất",
          "Phường Cầu Tre",
          "Phường Đằng Giang",
          "Phường Đông Khê",
          "Phường Gia Viên",
          "Phường Lạc Viên",
          "Phường Lê Lợi",
          "Phường Lương Khánh Thiện",
          "Phường Máy Chai",
          "Phường Máy Tơ",
          "Phường Vạn Mỹ",
        ],
      },
      {
        name: "Quận Lê Chân",
        wards: [
          "Phường An Biên",
          "Phường An Dương",
          "Phường Cát Dài",
          "Phường Đông Hải",
          "Phường Dư Hàng",
          "Phường Dư Hàng Kênh",
          "Phường Hàng Kênh",
          "Phường Hồ Nam",
          "Phường Kênh Dương",
          "Phường Niệm Nghĩa",
          "Phường Nghĩa Xá",
          "Phường Trại Cau",
          "Phường Trần Nguyên Hãn",
          "Phường Vĩnh Niệm",
        ],
      },
    ],
  },
  {
    name: "Bình Dương",
    districts: [
      {
        name: "Thành phố Thủ Dầu Một",
        wards: [
          "Phường Chánh Mỹ",
          "Phường Chánh Nghĩa",
          "Phường Định Hòa",
          "Phường Hiệp An",
          "Phường Hiệp Thành",
          "Phường Hòa Phú",
          "Phường Phú Cường",
          "Phường Phú Hòa",
          "Phường Phú Lợi",
          "Phường Phú Mỹ",
          "Phường Phú Tân",
          "Phường Phú Thọ",
          "Phường Tân An",
          "Phường Tương Bình Hiệp",
        ],
      },
      {
        name: "Thành phố Dĩ An",
        wards: [
          "Phường An Bình",
          "Phường Bình An",
          "Phường Bình Thắng",
          "Phường Dĩ An",
          "Phường Đông Hòa",
          "Phường Tân Bình",
          "Phường Tân Đông Hiệp",
        ],
      },
      {
        name: "Thành phố Thuận An",
        wards: [
          "Phường An Phú",
          "Phường An Thạnh",
          "Phường Bình Chuẩn",
          "Phường Bình Hòa",
          "Phường Bình Nhâm",
          "Phường Hưng Định",
          "Phường Lái Thiêu",
          "Phường Thuận Giao",
          "Phường Vĩnh Phú",
        ],
      },
    ],
  },
  {
    name: "Đồng Nai",
    districts: [
      {
        name: "Thành phố Biên Hòa",
        wards: [
          "Phường An Bình",
          "Phường Bình Đa",
          "Phường Bửu Hòa",
          "Phường Bửu Long",
          "Phường Hóa An",
          "Phường Hòa Bình",
          "Phường Hố Nai",
          "Phường Long Bình",
          "Phường Long Bình Tân",
          "Phường Phước Tân",
          "Phường Quang Vinh",
          "Phường Quyết Thắng",
          "Phường Tam Hiệp",
          "Phường Tam Hòa",
          "Phường Tân Biên",
          "Phường Tân Hạnh",
          "Phường Tân Hiệp",
          "Phường Tân Hòa",
          "Phường Tân Mai",
          "Phường Tân Phong",
          "Phường Tân Tiến",
          "Phường Tân Vạn",
          "Phường Thống Nhất",
          "Phường Thanh Bình",
          "Phường Trảng Dài",
          "Phường Trung Dũng",
        ],
      },
      {
        name: "Thành phố Long Khánh",
        wards: [
          "Phường Bảo Vinh",
          "Phường Bình Lộc",
          "Phường Suối Tre",
          "Phường Xuân An",
          "Phường Xuân Bình",
          "Phường Xuân Hòa",
          "Phường Xuân Lập",
          "Phường Xuân Tân",
          "Phường Xuân Thanh",
          "Phường Xuân Trung",
        ],
      },
    ],
  },
  {
    name: "Khánh Hòa",
    districts: [
      {
        name: "Thành phố Nha Trang",
        wards: [
          "Phường Lộc Thọ",
          "Phường Ngọc Hiệp",
          "Phường Phước Hải",
          "Phường Phước Hòa",
          "Phường Phước Long",
          "Phường Phước Tân",
          "Phường Phước Tiến",
          "Phường Phương Sài",
          "Phường Phương Sơn",
          "Phường Tân Lập",
          "Phường Vạn Thắng",
          "Phường Vạn Thạnh",
          "Phường Vĩnh Hải",
          "Phường Vĩnh Hòa",
          "Phường Vĩnh Nguyên",
          "Phường Vĩnh Phước",
          "Phường Vĩnh Thọ",
          "Phường Vĩnh Trường",
          "Phường Xương Huân",
        ],
      },
      {
        name: "Thành phố Cam Ranh",
        wards: [
          "Phường Ba Ngòi",
          "Phường Cam Linh",
          "Phường Cam Lộc",
          "Phường Cam Lợi",
          "Phường Cam Nghĩa",
          "Phường Cam Phú",
          "Phường Cam Phúc Bắc",
          "Phường Cam Phúc Nam",
          "Phường Cam Thuận",
        ],
      },
    ],
  },
  {
    name: "Thừa Thiên Huế",
    districts: [
      {
        name: "Thành phố Huế",
        wards: [
          "Phường An Cựu",
          "Phường An Đông",
          "Phường An Hòa",
          "Phường An Tây",
          "Phường Hương Long",
          "Phường Hương Sơ",
          "Phường Kim Long",
          "Phường Phú Bình",
          "Phường Phú Hậu",
          "Phường Phú Hội",
          "Phường Phú Nhuận",
          "Phường Phú Thuận",
          "Phường Phước Vĩnh",
          "Phường Tây Lộc",
          "Phường Thuận Hòa",
          "Phường Thuận Lộc",
          "Phường Thuận Thành",
          "Phường Trường An",
          "Phường Vĩnh Ninh",
          "Phường Xuân Phú",
        ],
      },
    ],
  },
  {
    name: "Nghệ An",
    districts: [
      {
        name: "Thành phố Vinh",
        wards: [
          "Phường Bến Thủy",
          "Phường Cửa Nam",
          "Phường Đội Cung",
          "Phường Đông Vĩnh",
          "Phường Hà Huy Tập",
          "Phường Hồng Sơn",
          "Phường Hưng Bình",
          "Phường Hưng Dũng",
          "Phường Hưng Phúc",
          "Phường Lê Lợi",
          "Phường Lê Mao",
          "Phường Quán Bàu",
          "Phường Quang Trung",
          "Phường Trung Đô",
          "Phường Trường Thi",
          "Phường Vinh Tân",
        ],
      },
    ],
  },
  {
    name: "Thanh Hóa",
    districts: [
      {
        name: "Thành phố Thanh Hóa",
        wards: [
          "Phường Ba Đình",
          "Phường Đông Cương",
          "Phường Đông Hải",
          "Phường Đông Hương",
          "Phường Đông Sơn",
          "Phường Đông Thọ",
          "Phường Đông Vệ",
          "Phường Hàm Rồng",
          "Phường Lam Sơn",
          "Phường Nam Ngạn",
          "Phường Ngọc Trạo",
          "Phường Phú Sơn",
          "Phường Quảng Hưng",
          "Phường Quảng Thắng",
          "Phường Quảng Thành",
          "Phường Tân Sơn",
          "Phường Trường Thi",
          "Phường Thiệu Dương",
          "Phường Thiệu Khánh",
        ],
      },
    ],
  },
  {
    name: "Quảng Nam",
    districts: [
      {
        name: "Thành phố Tam Kỳ",
        wards: [
          "Phường An Mỹ",
          "Phường An Phú",
          "Phường An Sơn",
          "Phường An Xuân",
          "Phường Hòa Hương",
          "Phường Hòa Thuận",
          "Phường Phước Hòa",
          "Phường Tân Thạnh",
          "Phường Trường Xuân",
        ],
      },
      {
        name: "Thành phố Hội An",
        wards: [
          "Phường Cẩm An",
          "Phường Cẩm Châu",
          "Phường Cẩm Nam",
          "Phường Cẩm Phô",
          "Phường Cửa Đại",
          "Phường Minh An",
          "Phường Sơn Phong",
          "Phường Tân An",
          "Phường Thanh Hà",
        ],
      },
    ],
  },
  {
    name: "Quảng Ninh",
    districts: [
      {
        name: "Thành phố Hạ Long",
        wards: [
          "Phường Bạch Đằng",
          "Phường Bãi Cháy",
          "Phường Cao Thắng",
          "Phường Cao Xanh",
          "Phường Đại Yên",
          "Phường Giếng Đáy",
          "Phường Hà Khánh",
          "Phường Hà Lầm",
          "Phường Hà Phong",
          "Phường Hà Trung",
          "Phường Hà Tu",
          "Phường Hồng Gai",
          "Phường Hồng Hà",
          "Phường Hồng Hải",
          "Phường Hùng Thắng",
          "Phường Tuần Châu",
          "Phường Trần Hưng Đạo",
          "Phường Việt Hưng",
          "Phường Yết Kiêu",
        ],
      },
    ],
  },
  {
    name: "Long An",
    districts: [
      {
        name: "Thành phố Tân An",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường Khánh Hậu",
          "Phường Tân Khánh",
        ],
      },
    ],
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    districts: [
      {
        name: "Thành phố Vũng Tàu",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường Nguyễn An Ninh",
          "Phường Rạch Dừa",
          "Phường Thắng Nhất",
          "Phường Thắng Nhì",
          "Phường Thắng Tam",
        ],
      },
      {
        name: "Thành phố Bà Rịa",
        wards: [
          "Phường Hòa Long",
          "Phường Kim Dinh",
          "Phường Long Hương",
          "Phường Long Phước",
          "Phường Long Tâm",
          "Phường Long Toàn",
          "Phường Phước Hiệp",
          "Phường Phước Hưng",
          "Phường Phước Nguyên",
          "Phường Phước Trung",
        ],
      },
    ],
  },
  {
    name: "Tây Ninh",
    districts: [
      {
        name: "Thành phố Tây Ninh",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường Hiệp Ninh",
          "Phường Ninh Sơn",
          "Phường Ninh Thạnh",
        ],
      },
    ],
  },
  {
    name: "An Giang",
    districts: [
      {
        name: "Thành phố Long Xuyên",
        wards: [
          "Phường Bình Đức",
          "Phường Bình Khánh",
          "Phường Đông Xuyên",
          "Phường Mỹ Bình",
          "Phường Mỹ Hòa",
          "Phường Mỹ Long",
          "Phường Mỹ Phước",
          "Phường Mỹ Quý",
          "Phường Mỹ Thạnh",
          "Phường Mỹ Thới",
          "Phường Mỹ Xuyên",
        ],
      },
    ],
  },
  {
    name: "Kiên Giang",
    districts: [
      {
        name: "Thành phố Rạch Giá",
        wards: [
          "Phường An Bình",
          "Phường An Hòa",
          "Phường Phó Thọ",
          "Phường Rạch Sỏi",
          "Phường Vĩnh Bảo",
          "Phường Vĩnh Hiệp",
          "Phường Vĩnh Lạc",
          "Phường Vĩnh Lợi",
          "Phường Vĩnh Quang",
          "Phường Vĩnh Thanh",
          "Phường Vĩnh Thông",
        ],
      },
    ],
  },
  {
    name: "Tiền Giang",
    districts: [
      {
        name: "Thành phố Mỹ Tho",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường 10",
          "Phường Tân Long",
        ],
      },
    ],
  },
  {
    name: "Bến Tre",
    districts: [
      {
        name: "Thành phố Bến Tre",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường An Hội",
          "Phường Phú Khương",
          "Phường Phú Tân",
        ],
      },
    ],
  },
  {
    name: "Cà Mau",
    districts: [
      {
        name: "Thành phố Cà Mau",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 4",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 8",
          "Phường 9",
          "Phường Tân Thành",
          "Phường Tân Xuyên",
        ],
      },
    ],
  },
  {
    name: "Thái Nguyên",
    districts: [
      {
        name: "Thành phố Thái Nguyên",
        wards: [
          "Phường Cam Giá",
          "Phường Đồng Quang",
          "Phường Gia Sàng",
          "Phường Hoàng Văn Thụ",
          "Phường Hương Sơn",
          "Phường Phan Đình Phùng",
          "Phường Phú Xá",
          "Phường Quang Trung",
          "Phường Quang Vinh",
          "Phường Tân Lập",
          "Phường Tân Long",
          "Phường Tân Thành",
          "Phường Thịnh Đán",
          "Phường Tích Lương",
          "Phường Trung Thành",
          "Phường Trưng Vương",
          "Phường Túc Duyên",
        ],
      },
    ],
  },
  {
    name: "Nam Định",
    districts: [
      {
        name: "Thành phố Nam Định",
        wards: [
          "Phường Bà Triệu",
          "Phường Cửa Bắc",
          "Phường Cửa Nam",
          "Phường Hạ Long",
          "Phường Lộc Hạ",
          "Phường Lộc Hòa",
          "Phường Lộc Vượng",
          "Phường Mỹ Xá",
          "Phường Năng Tĩnh",
          "Phường Ngô Quyền",
          "Phường Nguyễn Du",
          "Phường Phan Đình Phùng",
          "Phường Quang Trung",
          "Phường Thống Nhất",
          "Phường Trần Đăng Ninh",
          "Phường Trần Hưng Đạo",
          "Phường Trần Quang Khải",
          "Phường Trần Tế Xương",
          "Phường Văn Miếu",
          "Phường Vị Hoàng",
          "Phường Vị Xuyên",
        ],
      },
    ],
  },
];

export default VIETNAM_PROVINCES;

// Address structure delimiter for reliable parsing
const ADDR_DELIM = "|||";

/**
 * Build a formatted address string from province/district/ward/detail
 * Uses a delimiter-based format for reliable parsing while maintaining human readability
 * Format: "Human readable address|||province|||district|||ward|||detail"
 */
export function buildAddressString({ province, district, ward, detail }) {
  // Human readable part comes first
  const parts = [detail, ward, district, province].filter(Boolean);
  const humanReadable = parts.join(", ");
  // Append structured data for reliable parsing
  return `${humanReadable}${ADDR_DELIM}${province || ""}${ADDR_DELIM}${district || ""}${ADDR_DELIM}${ward || ""}${ADDR_DELIM}${detail || ""}`;
}

/**
 * Build human-readable display string from address components
 */
export function formatAddressForDisplay({ province, district, ward, detail }) {
  const parts = [detail, ward, district, province].filter(Boolean);
  return parts.join(", ");
}

/**
 * Get the display version of an address (human-readable part only)
 */
export function getAddressDisplayString(address) {
  if (!address) return "";
  const delimIndex = address.indexOf(ADDR_DELIM);
  if (delimIndex !== -1) {
    return address.substring(0, delimIndex);
  }
  return address;
}

/**
 * Try to parse an address string back into components
 * Supports both new structured format and legacy format
 */
export function parseAddressString(address) {
  if (!address) return { province: "", district: "", ward: "", detail: "" };

  // Check for new delimiter-based format first
  const delimIndex = address.indexOf(ADDR_DELIM);
  if (delimIndex !== -1) {
    const parts = address.split(ADDR_DELIM);
    // parts[0] = human readable, parts[1] = province, parts[2] = district, parts[3] = ward, parts[4] = detail
    if (parts.length >= 5) {
      return {
        province: parts[1] || "",
        district: parts[2] || "",
        ward: parts[3] || "",
        detail: parts[4] || "",
      };
    }
  }

  // Legacy parsing: Try to match Vietnamese province names
  for (const prov of VIETNAM_PROVINCES) {
    if (address.includes(prov.name)) {
      for (const dist of prov.districts) {
        if (address.includes(dist.name)) {
          for (const w of dist.wards) {
            if (address.includes(w)) {
              const detail = address
                .replace(w, "")
                .replace(dist.name, "")
                .replace(prov.name, "")
                .replace(/,\s*/g, " ")
                .trim();
              return {
                province: prov.name,
                district: dist.name,
                ward: w,
                detail: detail,
              };
            }
          }
          const detail = address
            .replace(dist.name, "")
            .replace(prov.name, "")
            .replace(/,\s*/g, " ")
            .trim();
          return {
            province: prov.name,
            district: dist.name,
            ward: "",
            detail: detail,
          };
        }
      }
      const detail = address
        .replace(prov.name, "")
        .replace(/,\s*/g, " ")
        .trim();
      return { province: prov.name, district: "", ward: "", detail: detail };
    }
  }

  return { province: "", district: "", ward: "", detail: address };
}
